version: '3.8'

services:  
  arangodb:
    build:
      context: ./llm_cluster_api
      dockerfile: Dockerfile-DB
    container_name: arangodb-instance
    ports:
      - "8529:8529"
    volumes:
      - arangodb-data:/var/lib/arangodb3
    restart: always

  api:
    build: 
      context: ./llm_cluster_api
      dockerfile: Dockerfile-API
    environment:
      - ARANGODB_URL=http://arangodb-instance:8529
      - ARANGODB_USERNAME=root
      - ARANGODB_PASSWORD=123
    ports:
      - "8000:8000"
    depends_on:
      - arangodb
    restart: always
volumes: 
  arangodb-data: